kind: KafkaMirrorMaker2
apiVersion: kafka.strimzi.io/v1beta2
metadata:
  name: mm2-europe
  namespace: kafka-europe
  labels:
    app: mm2-europe
spec:
  version: 3.5.0
  replicas: 1
  connectCluster: "europe"
  clusters:
  - alias: "europe"
    bootstrapServers: europe-kafka-bootstrap.kafka-europe.svc:9092
    config:
      config.storage.replication.factor: 1
      offset.storage.replication.factor: 1
      status.storage.replication.factor: 1
  - alias: "us"
    bootstrapServers: us-kafka-bootstrap.kafka-us.svc:9092
  mirrors:
  - sourceCluster: "us"
    targetCluster: "europe"
    sourceConnector:
      config:
        replication.factor: 1
        offset-syncs.topic.replication.factor: 1
        sync.topic.acls.enabled: "false"
    heartbeatConnector:
      config:
        heartbeats.topic.replication.factor: 1
    checkpointConnector:
      config:
        checkpoints.topic.replication.factor: 1
        emit.checkpoints.interval.seconds: 5
    topicsPattern: ".*"
    groupsPattern: ".*"
  resources:
    requests:
      memory: 1Gi
    limits:
      memory: 1Gi