apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: us
  namespace: kafka-us
  labels:
    app: us
spec:
  kafka:
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: route
        tls: true
    resources:
      requests:
        memory: 2Gi
      limits:
        memory: 2Gi
    jvmOptions:
      -Xms: 1024m
      -Xmx: 1024m
    config:
      auto.create.topics.enable: "false"
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 2Gi
        deleteClaim: true
  zookeeper:
    replicas: 1
    resources:
      requests:
        memory: 1Gi
      limits:
        memory: 1Gi
    storage:
      type: persistent-claim
      size: 2Gi
      deleteClaim: true
  entityOperator:
    topicOperator: {}
    userOperator: {}